### ISSUE TITLE
Add react/no-find-dom-node to prevent usage of findDOMNode

### ISSUE THREAD

**Issue by ryansobol** [ryansobol/eslint-config-ryansobol#97]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-find-dom-node.md

**Comment by msartintarm** [comment]
Hey, I pulled in the newest version of the plugin and it's failing my Jasmine tests. This was supposed to be the newest way to refer to DOM nodes as of React 0.13.

With that in consideration, why is it set to fail instead of at least throw a warning? And also, can this act more like normal React deprecation warnings, honor the React version that is set in eslint, and not throw the warning for older versions of React? Right now my proejct eslint config specifies React version 0.13; hence I feel like this warning should not apply to it.

Thanks!
